language: python

python:
  - "3.6"

cache:
  apt: true
  pip: true

install:
  - apt install rename -y
  - pip install nbconvert
  - make install

before_deploy:
  - make docs
  - make build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  on:
    branch: master