name: Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python and pip
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.x'
    - name: Set up Nodejs and yarn
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install dependencies
      run: make install
    - name: Convert notebooks
      run: make docs
    - name: Build static files
      run: make build      
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vuepress/dist